### ISSUE TITLE
Custom Reconnect behavior

### ISSUE THREAD

**Issue by hansmbakker** [Marfusios/websocket-client#10]
I'm trying to build a client for Azure bot framework's DirectLine channel.

When reconnecting, the chat client has to request a new websocket url based on a watermark from the last message received. Then, the websocket client needs to reconnect to that **updated url**. That way the chat can smoothly continue from the last received message.

However, currently the websocket client already reconnects before I have the chance to set the updated url.

Can you implement e.g. a delegate that is executed before the Reconnect() is done?

Reference: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0

**Comment by Marfusios** [comment]
Hello, 

there is property `Url`. You can set a new uri there. 
The best way is to subscribe on `DisconnectionHappened`. 

Something like:
```csharp
WebsocketClient client = ...

client.DisconnectionHappened.Subscribe(type => {
  client.Url = new Uri("your new url");
});
```

As long as you subscribe by default (not on a different thread) it should work.

**Comment by hansmbakker** [comment]
That looks good, thank you!
