### ISSUE TITLE
client.NativeClient is allways null

### ISSUE THREAD

**Issue by GuyAgiv** [Marfusios/websocket-client#104]
Hi, 
i tried to set a custom header according to your sample within the factory block.

However, the NativeClient is allways null.

i cant open the connection without the custom header.
but NativeClient is allways null so i  assuming that the custom header i set in the Func body is just not send with the Start() function.

can you help me please how to instantiate the NativeClient (using the factory) cause the sample didnt work.

thank you !!!

**Comment by thebitbrine** [comment]
Can you please provide an example of the solution?
