### ISSUE TITLE
SSL certificates

### ISSUE THREAD

**Issue by arturo1212** [Marfusios/websocket-client#13]
Hi! I was wondering if I can specify SSL certificate pem files (cert and key). I need this feature in order to connect to some WebSocket servers.

**Comment by Marfusios** [comment]
Hello @arturo1212 
see this closed PR comment: https://github.com/Marfusios/websocket-client/pull/11#issuecomment-503916054 
I'm working on a better documentation right now.

**Comment by Marfusios** [comment]
Added documentation to readme 159c68adfdfdc177012f876fb2097de7516b3af2

**Comment by arturo1212** [comment]
Amazing! Thank you.
