### ISSUE TITLE
IWebsocketClient missing Send overload with byte[] payload

### ISSUE THREAD

**Issue by ekwus** [Marfusios/websocket-client#14]
Hi

Is there a reason IWebsocketClient does not have Send/SendInstant(byte[])?

Not having it means the client needs to be wrapped up in order to allow mocking in unit tests.

Thanks for a nice, simple, clean almost unit testable library :-)

Cheers

Dave

**Comment by Marfusios** [comment]
Hello, 

thanks for the message, definitely a mistake. 
I will add it there.

**Comment by Marfusios** [comment]
Fixed in 159c68adfdfdc177012f876fb2097de7516b3af2
