### ISSUE TITLE
No exception handling for bad "Send" commands? Leads to automatic disconnection? Any solution?

### ISSUE THREAD

**Issue by jonmdev** [Marfusios/websocket-client#151]
I am attempting to use your project as follows:

```
var url = new Uri("ws://localhost:4001/websocket");

var client = new WebsocketClient(url);
client.ReconnectTimeout = TimeSpan.FromSeconds(30);
client.ReconnectionHappened.Subscribe(info => Debug.WriteLine($"Reconnection happened, type: {info.Type}"));
client.DisconnectionHappened.Subscribe(info => Debug.WriteLine($"Disconnection happened, type: {info.Type}"));
client.MessageReceived.Subscribe(msg => Debug.WriteLine($"WebSocketClient Message: {msg}"));

await client.Start();

bool sent = client.Send("ping"); //supported message, works okay
Debug.WriteLine("SENT PING " + sent);

try {
    bool sentBad = client.Send("UNSUPPORTED MESSAGE"); //unsupported message, triggers 

    //Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.dll
    //Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
    //Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.dll
    //Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
    //Disconnection happened, type: Lost

    Debug.WriteLine("SENT BAD MSG " + sentBad);
}
catch (Exception ex) {
    Debug.WriteLine("WebsocketClient exception: " + ex.Message);
    //EXCEPTION NOT CAUGHT HERE AS THIS "SEND" COMMAND IS NOT THE ACTUAL "SEND" COMMAND (Just adds to queue)
}
```

In this code, `client.Send("ping");` is a server supported function, while `client.Send("UNSUPPORTED MESSAGE");` is not.

There must be some way to catch exceptions for bad send requests. Currently, it just gives the four "Exception Thrown" results above and then automatically disconnects the websocket. Try/Catch does not help here on `Send` because as per your code, `Send` just adds to a queue for sending and is not the actual send command.

I tried `await client.SendInstant("UNSUPPORTED MESSAGE")` in Try/Catch also but no benefit.

By contrast, if I use WebSocketSharp (which is bad for other reasons), I can do:

```
string url = "ws://localhost:4001/websocket"; //local server test
var ws = new WebSocket(url);
ws.OnMessage += (sender, e) => { Debug.WriteLine("WEBSOCKET RETURNS MESSAGE SAYS: " + e.Data); };
ws.OnOpen += (sender, e) => { Debug.WriteLine("OPENED WEBSOCKET CONNECTION | " + ws.ReadyState); ws.Send("ping"); };
ws.OnClose += (sender, e) => { Debug.WriteLine("CLOSED WEBSOCKET CONNECTION | " + ws.ReadyState); };
ws.OnError += (sender, e) => { Debug.WriteLine("WEBSOCKET CONNECTION ERROR | " + ws.ReadyState + " " + e.Message.ToString()); };

ws.Connect();
ws.Send("ping"); //works

Action<bool> sentAction = delegate (bool sent) { Debug.WriteLine("WEBSOCKET MESSAGE SENT " + sent; };

//this works for catching exception:
try { ws.SendAsync("UNSUPPORTED WEBSOCKET MESSAGE", sentAction); }
catch (Exception ex) { Debug.WriteLine("WEBSOCKET SEND ERROR " + ex.Message); }

//Output: 
//Exception thrown: 'System.PlatformNotSupportedException' in websocket-sharp.dll 
//"WEBSOCKET SEND ERROR Operation is not supported on this platform."

//websocket NOT closed
```

Is this a hole in your design? Or is there some way to catch the exception here? Thanks for your project and any help.

**Comment by Marfusios** [comment]
@jonmdev thanks for reporting this. 
Based on the `Operation is not supported on this platform` message, I assume this is the edge case where the specific .NET version used does not support the WebSocket protocol.

Definitely an opportunity to make it better in our lib, the method `client.SendInstant()` should throw this exception. 
` client.Send()` schedules sending via queue, so throwing an exception is impossible. 

Btw, maybe `DisconnectionHappened` stream gives you more info.

**Comment by jonmdev** [comment]
Thanks @Marfusios, yeah there are always endless edge cases and bugs and errors. I have decided to just run my own implementation based on `ClientWebSocket` as you did too. Easier to run my own system from the ground up so I can fix my own weird bugs as they pop up. Thanks in any case.
