### ISSUE TITLE
Supporting unit testing websockets with TestHost

### ISSUE THREAD

**Issue by sahb1239** [Marfusios/websocket-client#20]
Hello,

In order to unit test my client implementation I would like to use the TestHost class provided by ASP.NET Core.

The Testhost class however returns a [TestHost.WebSocketClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.testserver.createwebsocketclient?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-3.0) which has a method [ConnectAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.websocketclient.connectasync?view=aspnetcore-2.2#Microsoft_AspNetCore_TestHost_WebSocketClient_ConnectAsync_System_Uri_System_Threading_CancellationToken_) which returns a WebSocket. Since the websocket client requires that the type should be ClientWebSocket (which inherits from WebSocket).

I can see the only major blocker for changing to WebSocket is the connection and reconnection logic. This could possible be fixed by updating the factory method to handle connection. For example (line 19 in WebsocketClient):

`
Func<Uri, Task<WebSocket>> clientFactory = null
`

The default implementation would be (the CancellationToken would need to be updated):
```csharp
_clientFactory = clientFactory ?? (async (uri) =>
{
    var client = new ClientWebSocket
    {
        Options = { KeepAliveInterval = new TimeSpan(0, 0, 5, 0) }
    };
    await client.ConnectAsync(uri, CancellationToken.None).ConfigureAwait(false);
    return client;
}); 
```

This is however only part of the solution and will be a breaking change for the existing websocket client.

Are you willing to accept a PR to support this? Including a unit test with TestHost.

Sincerely,
Søren

**Comment by Marfusios** [comment]
Hello @sahb1239 ,

thanks for the idea, it would enable unit testing pretty nicely. 
We really miss better unit test coverage right now. 
Let me check it if there is any possible way without bringing breaking change.

**Comment by sahb1239** [comment]
Hello @Marfusios,

I was looking on the code yesterday and I found out that it can also be done by only updating one interface property: 
The property [NativeClient](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/IWebsocketClient.cs#L69) which should return a Websocket instead.

It would however be possible to cast to the ClientWebSocket if it's needed.

**Comment by Marfusios** [comment]
@sahb1239 

what do you think about: 
```csharp
_client = _clientFactory();
if (_client is ClientWebSocket clientSpecific)
{
	await clientSpecific.ConnectAsync(uri, token).ConfigureAwait(false);
}
```
?
It should be breaking-free update. 
Check branch https://github.com/Marfusios/websocket-client/commit/f19863f404cb6846c62aa53a9415d8bac5a97be7 

Could you please provide PR with unit tests?

**Comment by sahb1239** [comment]
@Marfusios 

It's still not breaking free since you change the interface to return a WebSocket instead of a ClientWebSocket. However it would be possible to just cast it. :)

I would recommend creating a new constructor with the following signature:
public WebsocketClient(Uri url, Func<Uri, CancellationToken, Task<WebSocket>> clientFactory = null)

I will provide a PR with unit test and the suggested changes to your branch today.

**Comment by Marfusios** [comment]
@sahb1239 
Thanks. That's true. 
Do you see any usecase where user/client needs to call connect() (or something async) by himself inside `clientFactory`? There are streams like Reconnection/Disconnection happened, so `clientFactory` should stay as simple as possible. 

In case it will be only for unit tests, I would go with a breaking-free approach. 
Doesn't change interface (just recast) and doesn't change clientFactory signature. 
I don't wanna bring any unnecessary logic to client/usage side.  

Or, maybe the best solution, we can implement it via constructor overload. 
Leave whole public API same as now (with `ClientWebSocket`), but provide a second internal constructor which takes `Func<Uri, CancellationToken, Task<WebSocket>> clientFactory`. Just for unit tests. 

```csharp
_client = _clientFactoryInternal != null ? 
                    (await _clientFactoryInternal(_url, _token)) : 
                    _clientFactory();
if (_client is ClientWebSocket clientSpecific)
{
	await clientSpecific.ConnectAsync(uri, token).ConfigureAwait(false);
}
```

**Comment by sahb1239** [comment]
@Marfusios 
I have now created a PR of what I would see as optional.

I would like to be able also from my own unit tests to be able to inject the WebSocket and internal would therefore not work for me.

You are welcome to update the PR as you see fit.

**Comment by Marfusios** [comment]
Thank you! Let me go through it.

**Comment by Marfusios** [comment]
PR was merged and it is ready to accept more unit tests https://github.com/Marfusios/websocket-client/pull/23

**Comment by sahb1239** [comment]
@Marfusios 
Looks very good with the additional unit tests. Thanks for merging

**Comment by Marfusios** [comment]
@sahb1239 
Thanks for your initiative. 
I'm still struggling with one thing, Every reconnecting and CloseAsync() throws this exception: 
```
2019-09-29 11:28:29 [Debug] [WEBSOCKET CLIENT] Reconnecting...
2019-09-29 11:28:29 [Error] [WEBSOCKET CLIENT] Error while listening to websocket stream, error: 'Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.TestHost.TestWebSocket'.'
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.TestHost.TestWebSocket'.
   at Microsoft.AspNetCore.TestHost.TestWebSocket.ReceiverSenderBuffer.ThrowNoReceive()
```

I didn't find anything meaningful on Google. Probably we got TestWebServer somehow badly configured or it doesn't terminate connection correctly. 

Do you have any idea?

**Comment by sahb1239** [comment]
@Marfusios 
It could be that the Client also disposes the TestHost and therefore [line 512](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/WebsocketClient.cs#L512) in `WebSocketClient` class will give problems.

If this is the case the `CreateClient` method in the `TestContext` class cold be changed such that it recreates the factory if it is disposed.

Do you have a example testcase which is having the problem?

**Comment by Marfusios** [comment]
Hmm, most likely you are right, but how to solve it. Also this line [225](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/WebsocketClient.cs#L225) throws exact same exception. 
There are two tests that log this exception: 
`Reconnecting_ShouldWorkAsExpected` 
`Stopping_ShouldWorkCorrectly` 

![image](https://user-images.githubusercontent.com/3494837/65830748-a0b84e00-e2b2-11e9-812f-267ef25cd210.png)

**Comment by sahb1239** [comment]
Well I have looked more closely on the issue and have found out that it happens because  client.ReceiveAsync(buffer, token) throws when the client is disposed. I don't think it's only related to the TestHostWebSocket and would probably also happen for a real web socket (I have not tested it).

The issue happens when the following events happens:
- client.ReceiveAsync is called (and waits for input) (line [542](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/WebsocketClient.cs#L542)) - task is now waiting for input

In another task the following events happens:
- Reconnect timer is triggering `LastChange` method (line [593](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/WebsocketClient.cs#L593))
- Method `ReconnectSynchronized` is called (line [619](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/WebsocketClient.cs#L619))
- Method `Reconnect` is called
- Client is disposed (line [511](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/WebsocketClient.cs#L511))
- Other logic etc.

The client.ReceiveAsync now throws a `ObjectDisposedException` which gives the error. The reconnection is not called 2 times since the check `if (_disposing || _reconnecting || _stopping || !IsStarted)` returns false.

The reconnection logic now reestablished the connection. I would recommend that you catch `ObjectDisposedException` in the Listen method below `OperationCanceledException`.

**Comment by Marfusios** [comment]
@sahb1239 
Hello, thanks for the investigation and PR. It seems that you are right. 
I'm going to make a few tests if there is any way to avoid this exception.

**Comment by Marfusios** [comment]
@sahb1239 
one more thanks for your reproduce steps, seems that I solved it by changing a call order to: 
![image](https://user-images.githubusercontent.com/3494837/66028174-d2245a00-e4fc-11e9-8901-6761b5248e69.png)
