### ISSUE TITLE
Change TimeoutMs int properties to TimeSpan

### ISSUE THREAD

**Issue by bontibon** [Marfusios/websocket-client#26]
It would be more idiomatic to have the timeout properties to be the TimeSpan type.

**Comment by Marfusios** [comment]
Hello, thanks for the idea, I thought about it already but never wanted to bring breaking change. 
I'm going to put it into future version 4.x

**Comment by Marfusios** [comment]
@bontibon implemented in [version 4.0](https://github.com/Marfusios/websocket-client/releases/tag/v4.0)
