### ISSUE TITLE
Adding PreReconnection handler

### ISSUE THREAD

**Issue by twity1337** [Marfusios/websocket-client#29]
Hello,
I think it would be cool, if there is some kind of preReconnection handler, which is always triggered just _before_ a reconnect happens. That way you should be able to control, whether a reconnect happens and in what way.

**For example / User story:**
- If the connection mistakenly disconnected by the server, I don't want to reconnect, since the error should be handled server side.
- If a reconnection happens, I want to send some kind of "welcome-back/reconnected"-message to restore the state where the previous connection has been before.

What do you think?

**Comment by Marfusios** [comment]
Hello @twity1337 ,

thanks for the idea, I see your use-case, let me think about it.

**Comment by AndrueCope** [comment]
I think this is needed and it should return a flag to indicate whether further attempts should be made. I am currently struggling to work out how to stop reconnection for cases where the server is never going to be ready (such as a miss-spelt URI, or server down for maintenance). So far I've not found anyway to have .Start() stop trying to connect.

**Comment by Marfusios** [comment]
@twity1337  implemented in [version 4.0](https://github.com/Marfusios/websocket-client/releases/tag/v4.0) 
There is a property `CancelReconnection` which can be set to `true` from DisconnectionHappened stream handler
