### ISSUE TITLE
Sending ping message and receive a pong message

### ISSUE THREAD

**Issue by shcizo** [Marfusios/websocket-client#30]
Hey

I have a question/problem/bug-ish. I am using your lib to connect to a wss service and I followed your simple console example. It  Since this is a low rate channel, the lib reconnects to the server as there hasn't been any messages coming through. But, since I use 
```
var factory = new Func<ClientWebSocket>(() => new ClientWebSocket
{
   Options =
   {
      KeepAliveInterval = TimeSpan.FromSeconds(30)
   }
});
```
and as I can see that my code pings the websocket server, and get a pong response, I kinda expected websocket-client to not trying to reconnect after the default 60 seconds because of no messages.
What are yout thoughts about this?

**Comment by Marfusios** [comment]
Hello @shcizo, 

interesting, I totally forgot that the native C# webscoket client could have some kind of ping-pong implemented internally. 
Unfortunately, that feature is undetectable for this WebsocketClient wrapper, so it is triggering reconnection. 

Do you have any public WebSocket server available where I could test that feature? 
As quick fix, you can leave `IsReconnectionEnabled = true` and set `ReconnectTimeoutMs = int.MaxValue`.

**Comment by shcizo** [comment]
Hey 

Unfortunately I can not help you with a server to test on. 

What purpose does ```IsReconnectionEnabled = true``` have when ```ReconnectTimeoutMs = int.MaxValue``` is set?

**Comment by Marfusios** [comment]
There are two reconnection situations:
1. no message came from the server in specified interval (`ReconnectTimeoutMs` + `IsReconnectionEnabled`)
2. listening thread is lost - broken network connection, a connection is forcibly closed by the server, etc. (`IsReconnectionEnabled`)

So the second situation will be still covered.

**Comment by shcizo** [comment]
Ah got it. Thanks for your time. If you would find a way to either implement the ping feature or somehow pick up the one that the native WebSocketClient does, that would be awesome.
