### ISSUE TITLE
Server Certificate Validation

### ISSUE THREAD

**Issue by ekwus** [Marfusios/websocket-client#31]
Hi

I'm wondering if anyone here understands how to achieve validating the servers certificate with this client?

I've tried to add a ServicePointManager.ServerCertificateValidationCallback to my code but it gets ignored and I can't find a way to set the ServerCertificateValidationCallback  on HttpClient (if it has one) but still use this library.

Any ideas would be appreciated, thanks.

Cheers

Dave

**Comment by Marfusios** [comment]
Hello, 

cannot really help, but quick google check gives: https://social.msdn.microsoft.com/Forums/vstudio/en-US/8fb8dc56-580e-42a0-a89d-706f2d1417aa/add-remotecertificatevalidationcallback-to-clientwebsocket?forum=netfxbcl 

Seems related

**Comment by ekwus** [comment]
Hey

Thanks for taking a look, I did see that thread but was hoping I had missed a change in direction, etc. I guess it will come along in a version of .NetStandard2.x later.

I really like your clean unit testable classes but unfortunately I'm going to have to move over to WebSocketSharp (net core port) so I can have certificate authentication.

Cheers

Dave
