### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by ZigmundL** [Marfusios/websocket-client#32]
Hello. I'm connected to exchange wss. 

`ws.MessageReceived.Subscribe(msg => OnMessage(msg.Text));
ws.ReconnectionHappened.Subscribe(type => OnReconnect(type));`

All other settings are default, reconnection is enabled etc.

After some time, about 4-5 hrs, I get reconnection function triggered with type "Lost".
OnReconnect function triggers new subscriptions to exchange channels. 

`OnReconnect(type){
ws.Send(subscribtion_message);
}`

But I do not receive any messages after. 
I have a thread that ticks every minute and watches time of received msgs and if it is not updating in OnMessage method then it forces reconnect. 
`ws.Reconnect();` 
It is said that it closes socket and I expect it to be as a new client.

My log looks like this:
Lost
ByUser
ByUser
...

It never reconnects with resuming subscriptions. 
If I restart my program it immediately connects, subscribes and works as supposed.

My local tests run fine. If I close tcp connection the program restores it and resubscribes to channels.

What could be wrong?

**Comment by Marfusios** [comment]
Hello, 

weird, ReconnectionStream should publish messages only when a new connection is established. 
Enable Verbose logging. 
Also, try `OnReconnect(type){ ws.SendInstant(subscribtion_message); }`

**Comment by Marfusios** [comment]
@ZigmundL any update? Try a new [version 4.0](https://github.com/Marfusios/websocket-client/releases/tag/v4.0)

**Comment by ZigmundL** [comment]
> @ZigmundL any update? Try a new [version 4.0](https://github.com/Marfusios/websocket-client/releases/tag/v4.0)
I had no time to inspect your lib, so I've just made a wrapper that disposes whole websocket-client if no messages were received in a minute. Then I reinit it and connect as a new client. It's working. Thx, I will take a look.

**Comment by ZigmundL** [comment]
I should definetely mention that i run my app on ubuntu with Mono-complete 5.10.1.20 (latest availiable version from their repository)

**Comment by ZigmundL** [comment]
Seems like update fixed this issue, my wrapper triggers no more. Internal reconnect does.

**Comment by Marfusios** [comment]
@ZigmundL perfect, thanks for cooperation.
