### ISSUE TITLE
Disposed WebsocketClients

### ISSUE THREAD

**Issue by faviann** [Marfusios/websocket-client#37]
I was wondering, is there a technical reason for not invoking the `OnCompleted` method on the WebsocketClient's subjects? 

The reason I'm asking is that I'm actually sometimes disposing of older sockets for new one and I've noticed the MessageReceived stream never gets `OnCompleted` invoked. This last bit prevents the automatic unsubscription and the amount of streams just keeps rising. 

It's not a complex issue (one-liner fix) but I'm wondering if I could be missing some reason.

PS: Hi, thanks for sharing the library. It's great and makes using Websockets even more fun/intuitive.

**Comment by Marfusios** [comment]
Hello @faviann, 

thanks for the issue, totally forgot about completion in Reactive extensions. 
I'm going to add it.

**Comment by Marfusios** [comment]
Implemented in version 4.1.77 https://github.com/Marfusios/websocket-client/commit/ddc14c62835b5b9ffb2b8dedcb12eab0b606e40b

**Comment by faviann** [comment]
Damn that was quicker than expected! Thanks that was exactly what I hoping for.
