### ISSUE TITLE
Websocket.Client DLL is not Signed with a Strong Name Key

### ISSUE THREAD

**Issue by IvanGit** [Marfusios/websocket-client#40]
Hello,

I use Websocket.Client from NuGet in my application. Because my application is signed I get the error while Websocket.Client dll loading:

Could not load file or assembly 'Websocket.Client, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Could you sign the assembly in NuGet package? Thank you.

**Comment by Marfusios** [comment]
Hello @IvanGit ,

I've enabled signing, try the latest version [4.1.83](https://www.nuget.org/packages/Websocket.Client/4.1.83). 
Let me know if it helped.

**Comment by IvanGit** [comment]
Yes, now it works as expected. The issue is resolved.
