### ISSUE TITLE
Auth, Origin, Sec-WebSocket-Protocol Support?

### ISSUE THREAD

**Issue by simplextech** [Marfusios/websocket-client#5]
I was experimenting with this last night and I could not find any method for supporting of authentication (basic auth) nor how to set the origin or sub protocol.  Are these websocket attributes not supported?

**Comment by Marfusios** [comment]
Hello, 

the second parameter to `WebsocketClient` is optional factory method for native .NET `ClientWebSocket`. 
You can set there whatever .NET framework supports. 

```chsarp
 using (var client = new WebsocketClient(url, () => new ClientWebSocket()
            {
                Options =
                {
                    Credentials = new NetworkCredential() { ... },
                    Proxy = ...
                }
            }))
{
}
```

**Comment by simplextech** [comment]
Thanks for this information.  I will give it a try.  Dumb questions but I'm new to .NET and C# as I have this all working with Python :)

**Comment by Marfusios** [comment]
Sure, C# could be a little complicated for newcomers, they still adding new functionality and syntactic sugars into the language... 
Python is nice and really straightforward, but unfortunately not statically typed. 

Let me know if everything works.

**Comment by dthisner** [comment]
Sorry to post in an closed bug/issue. 

@Marfusios Could you please provide an example how to set the origin? 
When I am looking up the "ClientWebSocket", it dosn't have an option to set the origin

**Comment by Marfusios** [comment]
@dthisner never used Origin. 
But according to [this](https://devcenter.heroku.com/articles/websocket-security#origin-header) it is defined as custom header, so something like this a guess: 

![image](https://user-images.githubusercontent.com/3494837/68975122-ae8a4a00-07f2-11ea-9b77-b021dcd489f5.png)
