### ISSUE TITLE
Pause main thread until specific message is received

### ISSUE THREAD

**Issue by Sn3b** [Marfusios/websocket-client#51]
I need to send a (varying) number of requests, to which I eventually get responses, but I need to somehow pause the main thread until I have got all those responses. The service I am querying sends  sequence numbers so I can identify the responses, but I'm really not sure how to best achieve this with the MessageReceived observable...

Are there any best practice to wait for specific responses?

Thanks!

**Comment by Marfusios** [comment]
Hello @Sn3b , 

show me some code. 
If you really need to block main thread, you can use `ManualResetEvent` exactly the same way as is described in readme but unblock it when received enough messages. 
```csharp
                client.MessageReceived.Subscribe(msg =>
                {
                    Log.Information($"Message received: {msg}");
                    if(someYourLogic)
                        ExitEvent.Set();
                });
```
https://github.com/Marfusios/websocket-client/blob/c49fefae08110bee5836b52c3a76f8e7593c94ad/test_integration/Websocket.Client.Sample/Program.cs#L76

**Comment by Sn3b** [comment]
Hey, thanks for your answer. This indeed what I have done, glad I was on the right path :)
Works beautiful :)
