### ISSUE TITLE
Improper conditional subscription examples

### ISSUE THREAD

**Issue by DrSoops** [Marfusios/websocket-client#56]
In the main [ReadMe](https://github.com/Marfusios/websocket-client/blob/master/README.md) there is the following example 
```
client
    .MessageReceived
    .Where(msg => msg.StartsWith("{"))
    .Subscribe(obj => { code1 });
```

In the above msg is not a string but a [ResponseMessage](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/ResponseMessage.cs) so it does not have a StartsWith method.
Should be `msg.Text.StartsWith`

Maybe add a comment saying it needs a null check or check MessageType to make sure it is text. I haven't seen what happens when a single websocket sends both text and binary so can't comment too much on this.

**Comment by Marfusios** [comment]
Thanks @DrSoops, good catch. 
Readme was not updated somewhere in the past when streamed message type changed.  
Fixed.

**Comment by DrSoops** [comment]
I'm also looking more into MSDN's [How to: Implement an Observer](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-implement-an-observer), if I get something that looks clean I'll throw a new example at you. Copy pasta advanced examples are always helpful for usability.
