### ISSUE TITLE
no support for events?

### ISSUE THREAD

**Issue by muteddisk** [Marfusios/websocket-client#6]
Hi,

Any reason you aren't raising an event on error/connect/disconnect/reconnect?

thanks

**Comment by Marfusios** [comment]
Hello, 

there are streams: 
```csharp
        /// <summary>
        /// Stream for reconnection event (triggered after the new connection) 
        /// </summary>
        public IObservable<ReconnectionType> ReconnectionHappened;

        /// <summary>
        /// Stream for disconnection event (triggered after the connection was lost) 
        /// </summary>
        public IObservable<DisconnectionType> DisconnectionHappened;
```

The first one sends type `ReconnectionType.Initial` right after the first connection to server. 
Let me know if you miss anything.

**Comment by muteddisk** [comment]
They work but with simple code. Something complicated a bit I get signature incompatible with your subscribe function. Thanks for the effort but like I always say. Better served on your own. I made own library instead

**Comment by Marfusios** [comment]
@muteddisk 
Most likely you forgot namespace. 
```csharp
using System;
```
It is a feature of [reactive extensions](http://reactivex.io/), they implemented extension method `Subscribe()` impractically under `System` namespace. 
Native C# events are very prone to mistakes and memory leaks, so Rx.NET is nice alternative and also is powerful tool for realtime streams environment.

**Comment by muteddisk** [comment]
Nope, it's in there. 

![image](https://user-images.githubusercontent.com/30062459/55082836-c69d3580-5078-11e9-8763-f63cc3cdd06c.png)
![image](https://user-images.githubusercontent.com/30062459/55082919-e7fe2180-5078-11e9-858c-77dfb28319c1.png)
![image](https://user-images.githubusercontent.com/30062459/55082945-f77d6a80-5078-11e9-96a0-4455716337b0.png)
