### ISSUE TITLE
Remove tag "cryptocurrency" from repo

### ISSUE THREAD

**Issue by selimrecep** [Marfusios/websocket-client#60]
![image](https://user-images.githubusercontent.com/16990318/87590825-19788180-c6f0-11ea-932e-f7d02d983ff5.png)

If there isn't easter egg about cryptocurrency in the codes :D, I think that is a mistake

**Comment by Marfusios** [comment]
Good catch @selimrecep , this library was born from https://github.com/Marfusios/bitfinex-client-websocket 
That's why the tag came along with, done.
