### ISSUE TITLE
Change Authentication Header on Reconnect

### ISSUE THREAD

**Issue by julianfromano** [Marfusios/websocket-client#65]
Hi, great library.
I'm sending an authentication header when connecting. I'm adding the header in the factory in the connect and it works fine.
I'm worried that at recconect, if the header is expired i need a new one, but i can't do it, i'm trying to change the header in the NativeClient property in the reconnect event handler but it doesn't work as the web socket is already initiated.
Is there a way to do this?

If not I will have to manage the reconnection manually.

Thanks!

**Comment by Marfusios** [comment]
Hello @julianfromano , 

are you using factory method? 
```csharp
var factory = new Func<ClientWebSocket>(() => new ClientWebSocket
{
    Options =
    {
        KeepAliveInterval = TimeSpan.FromSeconds(5),
        Proxy = ...
        ClientCertificates = ...
    }
});

var client = new WebsocketClient(url, factory);
client.Start();
```

If so, you can change headers there. That callback is called on every reconnection.

**Comment by julianfromano** [comment]
Thanks, you are right. I wanted to fix something it wasn't wroken
