### ISSUE TITLE
Subscribe for special message by GUID?

### ISSUE THREAD

**Issue by freeze-out** [Marfusios/websocket-client#68]
Hey.

Thank you for your library. It's awesome :)

But I have a question. My client sends a message with a GUID to the WebSocket server. The server responds to it with the sent GUID and the data. So every request can be assigned to the request made by the client.
I am not so familiar with the IObserver pattern. The MessageReceived property provides me that funcationality.

I wish like to do something like that while my WebSocket server is running:

```
public Task<Data> GetDataAsync()
{            
            var requestId = Guid.NewGuid().ToString();  
            var responseTask = WebSocket
                .MessageReceived
                .Timeout(TimeSpan.FromSeconds(15))
                .FirstOrDefaultAsync(message => message.Text.Contains(requestId));
            
            WebSocket.Send(requestId);

            var responseMessage = await responseTask;
            
            return Parse(responseMessage);
}
```

That's maybe not the correct implemantation but maybe you got my intention? I want to send multiple request messages in parallel and I want to subscribe that single response message the server sends to me. Best would be if only one subscriber subscribes to the message with the request ID while the others don't have to check the message anymore when one picked it. The message is only for the one consumer who send the request id.

Thanks for your help :)

**Comment by Marfusios** [comment]
Hello @freeze-out ,

thanks, glad to hear that. 

Great question, I've already been thinking about it in the past. 
But always solved it in a different way, like producer-consumer without suppressing that native dual-channel approach. 
Where one side of the application is sending requests and another part handling all responses one-by-one, so I've successfully avoided the necessity to map exactly the request to a single response. 

But I see use-cases where that approach could be very convenient and simplify API usage from the client/caller point of view. 
So you gonna abstract that dual-channel into a single sync call. 

I believe your code is very accurate. 
I tried something like this and it seems to be working as expected: 

```csharp
private static async Task SendPingRequestAndWaitForResponse(IWebsocketClient client)
{
    try
    {
        var responseStream = client
            .MessageReceived
            .Where(x => x.Text.Contains("pong"))
            .Timeout(TimeSpan.FromSeconds(3))
            .FirstOrDefaultAsync()
            .ToTask();

        client.Send("ping");

        var result = await responseStream;
        Log.Information("Ping-pong response received, message: {0}", result);
    }
    catch (TimeoutException e)
    {
        Log.Error("Ping-pong response didn't arrive on time");
    }
}
```

Just please check whether that `responseStream` is correctly disposed, so `client.MessageReceived` does not have dead observers that could lead to memory leaks.

**Comment by Marfusios** [comment]
It seems that we can remove `.ToTask()` and just await `IObservable`. 
https://stackoverflow.com/questions/27415098/why-is-it-possible-to-await-an-rx-observable 

Also, I've checked 'observers' collection and that `.FirstOrDefaultAsync()` correctly finish the stream, so there is no memory leak.

**Comment by Marfusios** [comment]
Or if you wanna avoid `TimeoutException`: 

1. with 'Buffer':
```csharp
private static async Task SendPingRequestAndWaitForResponse(IWebsocketClient client)
{
    var responseStream = client
        .MessageReceived
        .Where(x => x.Text.Contains("pong"))
        .Buffer(TimeSpan.FromSeconds(3), 1)
        .Select(x => x.FirstOrDefault())
        .FirstOrDefaultAsync();

    client.Send("ping");

    var result = await responseStream;

    if(result != null)
        Log.Information("Ping-pong response received, message: {0}", result);
    else
        Log.Error("Ping-pong response didn't arrive on time");
}
```


2. with 'Amb':
```csharp
private static async Task SendPingRequestAndWaitForResponse(IWebsocketClient client)
{
    var responseStream = client
        .MessageReceived
        .Where(x => x.Text.Contains("pong"))
        .Amb(Observable.Return(default(ResponseMessage)).Delay(TimeSpan.FromSeconds(3)))
        .FirstOrDefaultAsync();

    client.Send("ping");

    var result = await responseStream;

    if(result != null)
        Log.Information("Ping-pong response received, message: {0}", result);
    else
        Log.Error("Ping-pong response didn't arrive on time");
}
```

**Comment by freeze-out** [comment]
Thanks for your help. I think I got enough input now :)

Never heard of Amb but my first guess is that it fullfils exactly the "while the others don't have to check the message anymore" requirement. I'll try that even it is not so important to me.

I think that solved my problem so far and the topic can be closed.

I might have some other questions later. I am just diving into your library. Before I was using the native WebSocket Client and it seemed to me very basic and couldn't believe people implement it again and again.

Thank you again, very great and fundamental answers 👍
