### ISSUE TITLE
No way to terminate the connection with custom close codes, or get the status code of a server-triggered close handshake

### ISSUE THREAD

**Issue by trinitrotoluene** [Marfusios/websocket-client#7]
I know that the client will automatically close and "clean up" when disposed, but being unable to close and send custom close codes hides important functionality from `ClientWebSocket` which itself _does_ support sending close codes out of the box.

This makes it impossible to use the client in any scenario where you'd like to send custom error codes to the server (for which a reserved range exists in RFC6455 itself).

Thanks for a great package though, makes it really easy to get started chatting over the protocol!

**Edit**

Additionally there's no way to get the optional 2-byte status code that servers may send when closing connections (RFC section 5.1.1) when subscribing to `DisconnectionHappened`.

**Comment by Marfusios** [comment]
Hello, 

thanks for the info. 
Could you prepare some PR? I've no remote server where I can test this functionality.

**Comment by Marfusios** [comment]
Implemented in 159c68adfdfdc177012f876fb2097de7516b3af2 
You can now call method `Close(...)` with custom close codes. 
Also, the ability to get current native client via `client.NativeClient` which contains properties with close status codes from the server.
