### ISSUE TITLE
How can i change User-Agent?

### ISSUE THREAD

**Issue by hiagocmendes** [Marfusios/websocket-client#72]
Hello how are you?
I tried to change the User-Agent but I couldn't find where to do it, could you tell if there is a way?

**Comment by Marfusios** [comment]
Hello @hiagocmendes ,

try to use client factory with custom settings. 
Here is a documentation: [advanced configuration](https://github.com/Marfusios/websocket-client#advanced-configuration)

**Comment by hiagocmendes** [comment]
Yes, I tried to do this via headers with the factory, but it returns the following message: "the 'User-Agent' header must be modified using the appropriate property or method."

I managed to change using reflection only. Apparently it worked without any problem.

**Comment by hiagocmendes** [comment]
This is my code.

**For lay people:**
To use this function, you do not need to call it when creating each client, you only need to use it when starting the application or before using WebSocket, just once.

`System.Reflection.Assembly a = typeof(System.Net.HttpWebRequest).Assembly;
                foreach (System.Reflection.FieldInfo f in a.GetType("System.Net.HeaderInfoTable").GetFields(System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static))
                {
                    if (f.Name == "HeaderHashTable")
                    {
                        System.Collections.Hashtable hashTable = f.GetValue(null) as System.Collections.Hashtable;
                        foreach (string sKey in hashTable.Keys)
                        {
                            object headerInfo = hashTable[sKey];
                            foreach (System.Reflection.FieldInfo g in a.GetType("System.Net.HeaderInfo").GetFields(System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance))
                            {
                                if (g.Name == "IsRequestRestricted" && sKey == "User-Agent")
                                {
                                    bool b = (bool)g.GetValue(headerInfo);
                                    if (b)
                                    {
                                        g.SetValue(headerInfo, false);
                                    }
                                }
                            }
                        }
                    }
                }`

**Comment by Marfusios** [comment]
@hiagocmendes crazy :O thanks for solution
