### ISSUE TITLE
How to set subprotocol?

### ISSUE THREAD

**Issue by frankhommers** [Marfusios/websocket-client#73]
The websocket protocol supports "subprotocols" and negotiation regarding these. 
(It's a list before the connection happens)

I cannot find any way to set this, am I missing something?

**Comment by frankhommers** [comment]
Through the factory ;-)

**Comment by Yanik39** [comment]
Hey,
Do you mind sharing the way to set the subprotocols?

**Comment by andrewmd5** [comment]
So did this get removed? Because the factory subprotocol property has no setter.
